version: '3.1'
services:
  odoo15:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./src/odoo/addons:/mnt/addons
#      - ./src/enterprise:/mnt/enterprise
      - ./src/themes:/mnt/themes
      - ./src/gonetAddons:/mnt/gonetAddons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5434:5432"
volumes:
  odoo-web-data:
  odoo-db-data:
